"use client"

import Head from 'next/head';
import Row from '@/components/Row';
import {Banner} from '@/components/Banner';
import { requests } from '@/lib/request';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <Banner />
          <Row
            title="NETFLIX ORIGUINALS"
            fetchUrl={requests.feachNetflixOriginals}
            isLargeRow
          />
          <Row title="Top Rated" fetchUrl={requests.feactTopRated} />
          <Row title="Action Movies" fetchUrl={requests.feactActionMovies} />
          <Row title="Comedy Movies" fetchUrl={requests.feactComedyMovies} />
          <Row title="Horror Movies" fetchUrl={requests.feactHorrorMovies} />
          <Row title="Romance Movies" fetchUrl={requests.feactRomanceMovies} />
          <Row title="DOcumentaries" fetchUrl={requests.feactDocumentMovies} />
        </div>
      </main>
    </>
  )
}
