"use client"

import Head from 'next/head';
import styles from '@/styles/Login.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App" style={{position: "relative"}}>
          <div className={styles.imgarea}>
            <div className={styles.img}>
            </div>
          </div>
          <img
            className={styles.logo}
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1920px-Netflix_2015_logo.svg.png"
            alt="Netflix Logo"
          />
          <div className={styles['login-form']}>
            <h1>ログイン</h1>
            <button className={styles['login-button']}>ログイン</button>
          </div>
        </div>
      </main>
    </>
  )
}